# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'/var/www/python/ville/proj/static/uploads/avatar'),
        ),
        migrations.AddField(
            model_name='person',
            name='karma',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
