# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirmation',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
        migrations.AddField(
            model_name='person',
            name='guests',
            field=models.ManyToManyField(related_name='_person_guests_+', to=settings.AUTH_USER_MODEL, verbose_name='guests'),
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(blank=True, choices=[(b'ua', 'Ukranian'), (b'ru', 'Russian'), (b'en', 'English')], default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
