# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160503_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='author',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
