# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20160503_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='karma',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='karma',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
